apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stolon.keeper.fullname" . }}
  labels:
    {{- include "stolon.keeper.labels" . | nindent 4 }}
type: Opaque
data:
  stkeeper-pg-su-username: {{ default "postgres" .Values.keeper.security.suUsername | b64enc }}
  stkeeper-pg-su-password: {{ default "postgres" .Values.keeper.security.suPassword | b64enc }}
  stkeeper-pg-repl-username: {{ default "replication" .Values.keeper.security.replUsername | b64enc }}
  stkeeper-pg-repl-password: {{ default "replication" .Values.keeper.security.replPassword | b64enc }}
