apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stolon.keeper.fullname" . }}
  labels:
    app: {{ include "stolon.name" . }}
    chart: {{ include "stolon.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  stkeeper-pg-su-username: {{ default "postgres" .Values.keeper.security.suUsername | b64enc }}
  stkeeper-pg-su-password: {{ default "postgres" .Values.keeper.security.suPassword | b64enc }}
  stkeeper-pg-repl-username: {{ default "replication" .Values.keeper.security.replUsername | b64enc }}
  stkeeper-pg-repl-password: {{ default "replication" .Values.keeper.security.replPassword | b64enc }}
