apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "stolon.init-cluster.fullname" . }}
  labels:
    {{- include "stolon.init-cluster.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      labels:
        {{- include "stolon.init-cluster.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      initContainers:
      - name: {{ include "stolon.init-cluster.fullname" . }}-wait-etcd
        image: {{ .Values.etcdImage.repository }}:{{ .Values.etcdImage.tag }}
        imagePullPolicy: {{ .Values.etcdImage.pullPolicy }}
        command:
        - /bin/bash
        - -ec
        - |
          echo "Waiting until etcd cluster becomes healthy"
          while true; do
            echo "Checking etcd cluster health"
            etcdctl endpoint health --cluster --endpoints {{ include "stolon.store.endpoints" . }} && break
            echo
            sleep 5
          done
      containers:
      - name: {{ include "stolon.init-cluster.fullname" . }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - stolonctl
        args:
        - init
        - --yes
        env:
        - name: STOLONCTL_CLUSTER_NAME
          value: {{ .Values.clusterName }}
        - name: STOLONCTL_STORE_BACKEND
          value: {{ .Values.store.backend }}
        - name: STOLONCTL_STORE_ENDPOINTS
          value: {{ include "stolon.store.endpoints" . }}
