{{- if .Values.clusterSpec }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "stolon.fullname" . }}-cluster-spec
  labels:
    {{- include "stolon.labels" . | nindent 4 }}
data:
  cluster-spec.json: |
    {{ .Values.clusterSpec | toPrettyJson | nindent 4 }}
{{- end }}
